<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFrameworks>net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <ImplicitUsings>enable</ImplicitUsings>
	<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
	<Version>1.0.0-beta</Version>
	<Authors>Carlos Jimenez</Authors>
	<Company>Tech Gems</Company>
	<Product>Vite.NET</Product>
	<Description>Vite.NET is an integration tool for MVC and Razor pages backends.</Description>
	<RepositoryType>git</RepositoryType>
	<RepositoryUrl>https://github.com/techgems/Vite.NET</RepositoryUrl>
	<PackageProjectUrl>https://vite-dotnet.techgems.net/</PackageProjectUrl>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageTags>vite;vite-integration;react;svelte;vue;lit;solidjs</PackageTags>
	<PackageId>TechGems.ViteDotNet</PackageId>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<PackageReleaseNotes>
		- Update to .NET 10.0 support
		- Update to TechGems.StaticComponents 1.3.2
		- Obsolete old config object.
	</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
	<Content Remove="_ViewImports.cshtml" />
  </ItemGroup>

  <ItemGroup>
	<None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TechGems.StaticComponents" Version="1.3.2" />
	<PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Components\_ViewImports.cshtml" />
  </ItemGroup>

</Project>
